### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineers

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "George",
  "techStack": "flask, django, spring"
}

###
GET http://localhost:8080/api/v1/software-engineers/1

###
PUT http://localhost:8080/api/v1/software-engineers/1
Content-Type: application/json

{
  "name": "James",
  "techStack": "flask, django, spring"
}
